# Generated by Django 4.2.30 on 2026-05-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Exercício')),
                ('muscle_group', models.CharField(choices=[('Peito', 'Peito'), ('Costas', 'Costas'), ('Ombros', 'Ombros'), ('Bíceps', 'Bíceps'), ('Tríceps', 'Tríceps'), ('Quadríceps', 'Quadríceps'), ('Posterior de coxa', 'Posterior de coxa'), ('Glúteos', 'Glúteos'), ('Panturrilhas', 'Panturrilhas'), ('Abdômen', 'Abdômen')], max_length=50, verbose_name='Grupo Muscular')),
                ('is_compound', models.BooleanField(default=True, verbose_name='É Composto?')),
            ],
            options={
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_executed', models.DateField(auto_now_add=True, verbose_name='Data de Execução')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback do Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Treino A, Costas, etc.', max_length=50, verbose_name='Nome da Sessão')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
            ],
            options={
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Treino')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='management.clientprofile', verbose_name='Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Séries')),
                ('reps', models.CharField(default='10-12', max_length=50, verbose_name='Repetições')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercisecatalog', verbose_name='Exercício')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.session')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.workout', verbose_name='Treino'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Horário')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmado'), ('X', 'Cancelado')], default='P', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='management.clientprofile')),
            ],
        ),
    ]
