# Generated by Django 4.2.30 on 2026-05-13 19:43

from django.db import migrations

def populate_exercises(apps, schema_editor):
    ExerciseCatalog = apps.get_model('training', 'ExerciseCatalog')
    
    exercises = [
        # Peito - Compostos
        {'name': 'Supino reto barra', 'muscle_group': 'Peito', 'is_compound': True},
        {'name': 'Supino reto halteres', 'muscle_group': 'Peito', 'is_compound': True},
        {'name': 'Supino inclinado barra', 'muscle_group': 'Peito', 'is_compound': True},
        {'name': 'Supino inclinado halteres', 'muscle_group': 'Peito', 'is_compound': True},
        {'name': 'Supino declinado', 'muscle_group': 'Peito', 'is_compound': True},
        {'name': 'Paralelas para peito', 'muscle_group': 'Peito', 'is_compound': True},
        {'name': 'Flexão de braço', 'muscle_group': 'Peito', 'is_compound': True},
        {'name': 'Chest press máquina', 'muscle_group': 'Peito', 'is_compound': True},
        # Peito - Isoladores
        {'name': 'Crucifixo reto', 'muscle_group': 'Peito', 'is_compound': False},
        {'name': 'Crucifixo inclinado', 'muscle_group': 'Peito', 'is_compound': False},
        {'name': 'Crossover polia alta', 'muscle_group': 'Peito', 'is_compound': False},
        {'name': 'Crossover polia média', 'muscle_group': 'Peito', 'is_compound': False},
        {'name': 'Peck deck / voador', 'muscle_group': 'Peito', 'is_compound': False},
        
        # Costas - Compostos
        {'name': 'Barra fixa pronada', 'muscle_group': 'Costas', 'is_compound': True},
        {'name': 'Barra fixa supinada', 'muscle_group': 'Costas', 'is_compound': True},
        {'name': 'Puxada frontal', 'muscle_group': 'Costas', 'is_compound': True},
        {'name': 'Remada curvada barra', 'muscle_group': 'Costas', 'is_compound': True},
        {'name': 'Remada cavalinho', 'muscle_group': 'Costas', 'is_compound': True},
        {'name': 'Remada unilateral halter', 'muscle_group': 'Costas', 'is_compound': True},
        {'name': 'Remada baixa polia', 'muscle_group': 'Costas', 'is_compound': True},
        {'name': 'Pulldown máquina', 'muscle_group': 'Costas', 'is_compound': True},
        {'name': 'Deadlift', 'muscle_group': 'Costas', 'is_compound': True},
        {'name': 'Rack pull', 'muscle_group': 'Costas', 'is_compound': True},
        # Costas - Isoladores
        {'name': 'Pullover halter', 'muscle_group': 'Costas', 'is_compound': False},
        {'name': 'Pullover polia', 'muscle_group': 'Costas', 'is_compound': False},
        
        # Ombros - Compostos
        {'name': 'Desenvolvimento militar barra', 'muscle_group': 'Ombros', 'is_compound': True},
        {'name': 'Desenvolvimento halteres', 'muscle_group': 'Ombros', 'is_compound': True},
        {'name': 'Arnold press', 'muscle_group': 'Ombros', 'is_compound': True},
        {'name': 'Desenvolvimento máquina', 'muscle_group': 'Ombros', 'is_compound': True},
        # Ombros - Isoladores
        {'name': 'Elevação lateral', 'muscle_group': 'Ombros', 'is_compound': False},
        {'name': 'Elevação frontal', 'muscle_group': 'Ombros', 'is_compound': False},
        {'name': 'Crucifixo invertido', 'muscle_group': 'Ombros', 'is_compound': False},
        {'name': 'Face pull', 'muscle_group': 'Ombros', 'is_compound': False},
        {'name': 'Encolhimento trapézio', 'muscle_group': 'Ombros', 'is_compound': False},
        
        # Bíceps - Isoladores
        {'name': 'Rosca direta barra', 'muscle_group': 'Bíceps', 'is_compound': False},
        {'name': 'Rosca alternada', 'muscle_group': 'Bíceps', 'is_compound': False},
        {'name': 'Rosca martelo', 'muscle_group': 'Bíceps', 'is_compound': False},
        {'name': 'Rosca concentrada', 'muscle_group': 'Bíceps', 'is_compound': False},
        {'name': 'Rosca Scott', 'muscle_group': 'Bíceps', 'is_compound': False},
        {'name': 'Rosca cabo', 'muscle_group': 'Bíceps', 'is_compound': False},
        {'name': 'Rosca inclinada halteres', 'muscle_group': 'Bíceps', 'is_compound': False},
        
        # Tríceps
        {'name': 'Tríceps pulley', 'muscle_group': 'Tríceps', 'is_compound': False},
        {'name': 'Tríceps corda', 'muscle_group': 'Tríceps', 'is_compound': False},
        {'name': 'Tríceps francês', 'muscle_group': 'Tríceps', 'is_compound': False},
        {'name': 'Tríceps testa', 'muscle_group': 'Tríceps', 'is_compound': False},
        {'name': 'Tríceps banco', 'muscle_group': 'Tríceps', 'is_compound': False},
        {'name': 'Paralelas para tríceps', 'muscle_group': 'Tríceps', 'is_compound': True},
        {'name': 'Supino fechado', 'muscle_group': 'Tríceps', 'is_compound': True},
        
        # Quadríceps
        {'name': 'Agachamento livre', 'muscle_group': 'Quadríceps', 'is_compound': True},
        {'name': 'Agachamento frontal', 'muscle_group': 'Quadríceps', 'is_compound': True},
        {'name': 'Leg press 45', 'muscle_group': 'Quadríceps', 'is_compound': True},
        {'name': 'Cadeira extensora', 'muscle_group': 'Quadríceps', 'is_compound': False},
        {'name': 'Hack squat', 'muscle_group': 'Quadríceps', 'is_compound': True},
        {'name': 'Bulgarian split squat', 'muscle_group': 'Quadríceps', 'is_compound': True},
        {'name': 'Passada / avanço', 'muscle_group': 'Quadríceps', 'is_compound': True},
        {'name': 'Afundo', 'muscle_group': 'Quadríceps', 'is_compound': True},
        {'name': 'Sissy squat', 'muscle_group': 'Quadríceps', 'is_compound': True},
        
        # Posterior de coxa
        {'name': 'Stiff', 'muscle_group': 'Posterior de coxa', 'is_compound': True},
        {'name': 'Romanian deadlift (RDL)', 'muscle_group': 'Posterior de coxa', 'is_compound': True},
        {'name': 'Mesa flexora', 'muscle_group': 'Posterior de coxa', 'is_compound': False},
        {'name': 'Cadeira flexora', 'muscle_group': 'Posterior de coxa', 'is_compound': False},
        {'name': 'Good morning', 'muscle_group': 'Posterior de coxa', 'is_compound': True},
        {'name': 'Nordic curl', 'muscle_group': 'Posterior de coxa', 'is_compound': False},
        
        # Glúteos
        {'name': 'Hip thrust', 'muscle_group': 'Glúteos', 'is_compound': True},
        {'name': 'Glute bridge', 'muscle_group': 'Glúteos', 'is_compound': True},
        {'name': 'Coice polia', 'muscle_group': 'Glúteos', 'is_compound': False},
        {'name': 'Abdução máquina', 'muscle_group': 'Glúteos', 'is_compound': False},
        {'name': 'Step-up', 'muscle_group': 'Glúteos', 'is_compound': True},
        
        # Panturrilhas
        {'name': 'Panturrilha em pé', 'muscle_group': 'Panturrilhas', 'is_compound': False},
        {'name': 'Panturrilha sentado', 'muscle_group': 'Panturrilhas', 'is_compound': False},
        {'name': 'Panturrilha no leg press', 'muscle_group': 'Panturrilhas', 'is_compound': False},
        {'name': 'Donkey calf raise', 'muscle_group': 'Panturrilhas', 'is_compound': False},
        
        # Abdômen
        {'name': 'Crunch', 'muscle_group': 'Abdômen', 'is_compound': False},
        {'name': 'Elevação de pernas', 'muscle_group': 'Abdômen', 'is_compound': False},
        {'name': 'Prancha', 'muscle_group': 'Abdômen', 'is_compound': True},
        {'name': 'Abdominal infra banco', 'muscle_group': 'Abdômen', 'is_compound': False},
        {'name': 'Ab wheel', 'muscle_group': 'Abdômen', 'is_compound': True},
        {'name': 'Russian twist', 'muscle_group': 'Abdômen', 'is_compound': True},
        {'name': 'Cable crunch', 'muscle_group': 'Abdômen', 'is_compound': False},
    ]
    
    for ex in exercises:
        ExerciseCatalog.objects.create(**ex)

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(populate_exercises),
    ]
