# Generated by Django 4.2.30 on 2026-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_populate_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
