# Generated by Django 4.2.30 on 2026-05-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_workout_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Dia da Semana'),
        ),
        migrations.AddField(
            model_name='session',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='training.dayofweek', verbose_name='Dias da Semana'),
        ),
    ]
