# Generated by Django 4.2.30 on 2026-05-25 13:37

from django.db import migrations


def populate_days_and_migrate(apps, schema_editor):
    DayOfWeek = apps.get_model('training', 'DayOfWeek')
    Session = apps.get_model('training', 'Session')

    # Create the 7 DayOfWeek instances
    days_dict = {}
    for d in range(7):
        day_obj, created = DayOfWeek.objects.get_or_create(day=d)
        days_dict[d] = day_obj

    # Migrate session day_of_week to days_of_week ManyToMany relationship
    for session in Session.objects.all():
        if session.day_of_week is not None:
            day_obj = days_dict.get(session.day_of_week)
            if day_obj:
                session.days_of_week.add(day_obj)

def rollback_days_and_migrate(apps, schema_editor):
    Session = apps.get_model('training', 'Session')
    # For rolling back, we populate the day_of_week integer field using the first associated day
    for session in Session.objects.all():
        first_day = session.days_of_week.all().first()
        if first_day:
            session.day_of_week = first_day.day
            session.save()

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_dayofweek_alter_session_day_of_week_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_days_and_migrate, rollback_days_and_migrate),
    ]
