# Generated by Django 4.2.30 on 2026-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_migrate_session_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='day_of_week',
        ),
        migrations.AlterField(
            model_name='session',
            name='days_of_week',
            field=models.ManyToManyField(related_name='sessions', to='training.dayofweek', verbose_name='Dias da Semana'),
        ),
    ]
